### ISSUE TITLE
Decrypt outside the plugin in CLI

### ISSUE THREAD

**Issue by Digitalin** [ssahara/dw-plugin-encryptedpasswords#18]
Hello,
The plugin works like a charm in DokuWiki. However, before responding to a thread on DokuWiki Forum, I have just checked the command in cli with the exemple given in the plugon documentation  : 
`echo  'U2FsdGVkX1/oynrOig+RoUwMNCHvJH2bcmQeAq2xaLI=' | openssl base64 -d |openssl aes-256-cbc -d`
which returns an error 
`enter aes-256-cbc decryption password:
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
139699213349312:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:537:
`
It seems the issue comes from differences between openssl releases ([here](https://stackoverflow.com/questions/34304570/how-to-resolve-the-evp-decryptfinal-ex-bad-decrypt-during-file-decryption) or [here](https://stackoverflow.com/questions/39637388/encryption-decryption-doesnt-work-well-between-two-different-openssl-versions/39641378#39641378)) with Digest.

**Comment by ssahara** [comment]
Hi,
My host is still running with Cent OS 6.5, here is my test run console display.
```` 
$ rpm -q openssl
openssl-1.0.1e-58.el6_10.x86_64
$ echo  'U2FsdGVkX1/oynrOig+RoUwMNCHvJH2bcmQeAq2xaLI=' | openssl base64 -d | openssl aes-256-cbc -d
enter aes-256-cbc decryption password: (type test)
hello world
````
I am sorry that I could not check further this issue, but I think it likely depends on openssl version.

**Comment by Digitalin** [comment]
Yes, it's likely an issue of openssl's version and the Digest used. As I am on Xubuntu 18.04, openssl version is 1.1.1
Do you have an idea of the command to run for this version ?

**Comment by ssahara** [comment]
Adding "-md md5" option worked using Ubuntu on WSL (WIndows 10)
````
$openssl version
OpenSSL 1.1.0g  2 Nov 2017
$ echo  'U2FsdGVkX1/oynrOig+RoUwMNCHvJH2bcmQeAq2xaLI=' | openssl base64 -d | openssl aes-256-cbc -d
enter aes-256-cbc decryption password:
bad decrypt
140268401725888:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:536:
$ echo  'U2FsdGVkX1/oynrOig+RoUwMNCHvJH2bcmQeAq2xaLI=' | openssl base64 -d | openssl aes-256-cbc -d -md md5
hello world
````

**Comment by Digitalin** [comment]
It works also on Ubuntu 18.04 with the -md parameter. There is just  a message of deprecated key but displays well the result.

```
 $ openssl version
OpenSSL 1.1.1  11 Sep 2018
$ echo "U2FsdGVkX1/oynrOig+RoUwMNCHvJH2bcmQeAq2xaLI=" | openssl base64 -d | openssl aes-256-cbc -d -md md5
enter aes-256-cbc decryption password:
 *** WARNING : deprecated key derivation used. Using -iter or -pbkdf2 would be better.
hello world%  
```

Thanks.
it could be useful to add the command in the wiki documentation.
