### ISSUE TITLE
Form Events and Compatibility with upcoming release Igor

### ISSUE THREAD

**Issue by splitbrain** [ssahara/dw-plugin-encryptedpasswords#20]
This plugin seems to make use of one or more form related action events that will be removed in the next DokuWiki release. Please have a look at https://www.patreon.com/posts/better-forms-58551930 for details.

My apologies if this has already been addressed in your code. If you have any questions on how to implement the needed changes please let me know.

**Comment by ssahara** [comment]
Thank you for informing me on this issue.
Encrypted Password plugin is already compatible with the next DokuWiki
release.

please update
https://docs.google.com/spreadsheets/d/193e-wrgej6DGqKQxcsghEbMR4OmQtDUmnmp9cfjF07o/edit#gid=0

2021年11月11日(木) 6:56 Andreas Gohr ***@***.***>:
